
identity=$1

echo '{}' > ./src/temp_canister_ids.json

version=$(jq -r .version ../../package.json)

echo '/** This is auto generated by scripts/pre-deploy.sh **/

export const version: string = "'$version'";' > ./src/.version.ts
