const fs = require("fs");
const path = require("path");
const packageJson = require(`${path.resolve("../../package.json")}`);

fs.writeFileSync(path.resolve(__dirname, "../src/temp_canister_ids.json"), JSON.stringify({}, null, 2));

const version = packageJson.version;

const content = `
/** This is auto generated by scripts/pre-deploy.js */

export const version: string = "${version}";
`;

fs.writeFileSync(path.resolve(__dirname, "../src/.version.ts"), content);
