import fs from "fs";
import path from "path";

const packageJSON = fs.readFileSync(
  path.resolve(__dirname, "../package.json"),
  {
    encoding: "utf8",
  },
);
const json = JSON.parse(packageJSON);
const version = json.version;

const content = `
/** This is auto generated by scripts/prepare.js */

export const version: string = "${version}"
`;

fs.writeFile(
  path.resolve(__dirname, "../apps/swap/src/.version.ts"),
  content,
  (err) => {
    console.log(err);
  },
);

fs.writeFile(
  path.resolve(__dirname, "../apps/info/src/.version.ts"),
  content,
  (err) => {
    console.log(err);
  },
);
